name: 'Pull Request another repository'
description: 'Used for pull request a copy of a folder to another repository'
inputs:
  source_folder:
    description: 'Source folder from origin'
    required: true
  destination_repo:
    description: 'Destination repository'
    required: true
  destination_folder:
    description: 'Destination folder to push the origin folder'
    required: false
  exclude_pattern:
    description: 'takes an rsync exclude pattern'
    required: false
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  destination_head_branch:
    description: 'The branch to create to push the changes. Cannot be master or main'
    required: true
  destination_base_branch:
    description: 'The branch into which you want your code merged.'
    required: false
    default: "main"
  pull_request_reviewers:
    description: 'Pull request reviewers users'
    required: false
  push_args:
    description: 'Add additional args in the push sequence'
    required: false
  message:
    description: 'Set a custom commit message'
    required: false 
  auto_publish:
    description: 'Instead of creating a pull-request, changes will be pushed to destination.'
    required: false
    default: false
  enable_safe_directory:
    description: 'Marks the temporary cloning directory as safe in git.'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-folder }}
    - ${{ inputs.destination-repo }}
    - ${{ inputs.destination-folder }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.destination-head-branch }}
    - ${{ inputs.destination-base-branch }}
    - ${{ inputs.pull-request-reviewers }}
branding:
  icon: 'git-commit'
  color: 'green'